apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: filestore-map-reduce
provisioner: pd.csi.storage.gke.io
allowVolumeExpansion: true
volumeBindingMode: Immediate
parameters:
  tier: standard
  network: default