apiVersion: v1
kind: Service
metadata:
  name: mapreduce-master
spec:
  clusterIP: None  # Required for StatefulSet
  selector:
    app: mapreduce-master
  ports:
    - protocol: TCP
      port: 50000
      targetPort: 50000
