apiVersion: v1
kind: Service
metadata:
  name: mapreduce-upload
spec:
  clusterIP: None  # Required for StatefulSet
  selector:
    app: mapreduce-upload
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
