apiVersion: apps/v1
kind: Deployment
metadata:
  name: mapreduce-workers
spec:
  replicas: 3  # Adjust as needed
  selector:
    matchLabels:
      app: mapreduce-worker
  template:
    metadata:
      labels:
        app: mapreduce-worker
    spec:
      containers:
        - name: worker
          image: ${REGION}-docker.pkg.dev/${PROJECT_ID}/map-reduce/worker:latest
          imagePullPolicy: Always
          env:
            - name: MASTER_ADDRESS
              value: "mapreduce-master-0.mapreduce-master.default.svc.cluster.local"
            - name: MASTER_PORT
              value: "50000"
            - name: WORKER_PORT
              value: "50000"
            - name: WORKER_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 50000
          volumeMounts:
            - name: mapreduce-pvc
              mountPath: /mapreduce
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
      volumes:
        - name: mapreduce-pvc
          persistentVolumeClaim:
            claimName: mapreduce-pvc
