apiVersion: v1
kind: Service
metadata:
  name: mapreduce-upload-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: mapreduce-upload
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000